export const PLANS = [
    {
        name:"Free",
        slug:"free",
        quota:10,
        pagesPerPdf:5,
        price:{
            amount:0,
            priceIds:{
                test:'',
                production:'',
            },
        },
    },
    {
        name:"Pro",
        slug:"pro",
        quota:50,
        pagesPerPdf:25,
        price:{
            amount:19.99,
            priceIds:{
                test:'price_1OJWP6Ayo8KG0FnXiNpcTDh8',
                production:'',
            },
        },
    },

]